FROM ubuntu:16.04
MAINTAINER Dawid Pilarski (dawid.pilarski@panicsoftware.com)
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN apt-get install -y wget
RUN add-apt-repository ppa:ubuntu-toolchain-r/test
#RUN add-apt-repository ppa:llvm-toolchain-trusty-5.0
#RUN add-apt-repository ppa:llvm-toolchain-trusty-6.0
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
RUN add-apt-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main"
RUN apt-get update
RUN apt-get install -y cmake
RUN apt-get install -y g++-4.9 g++-5 g++-6 g++-7 g++-8
RUN apt-get install -y clang-5.0 clang-6.0 clang-7


